on:
  push:
    branches: [ main ]
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./b2_test
      env:
        B2_TEST_KEY: ${{ secrets.B2_TEST_KEY }}
        B2_TEST_KEY_ID: ${{ secrets.B2_TEST_KEY_ID }}
        B2_TEST_BUCKET_ID: ${{ secrets.B2_TEST_BUCKET_ID }}
